// <auto-generated />
using MadarfigyeloWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MadarfigyeloWeb.Migrations
{
    [DbContext(typeof(TerepnaploContext))]
    partial class TerepnaploContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MadarfigyeloWeb.Models.Latogatas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Allapot")
                        .HasColumnType("int");

                    b.Property<int>("Datum")
                        .HasColumnType("int");

                    b.Property<string>("Faj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FiokaSzam")
                        .HasColumnType("int");

                    b.Property<string>("FiokakKora")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Megjegyzesek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OduId")
                        .HasColumnType("int");

                    b.Property<int>("Tevekenyseg")
                        .HasColumnType("int");

                    b.Property<int>("TojasSzam")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OduId");

                    b.ToTable("Latogatas");
                });

            modelBuilder.Entity("MadarfigyeloWeb.Models.Odu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BejaratiNyilasMm")
                        .HasColumnType("int");

                    b.Property<string>("Elohelykod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FelhelyezesModja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GpsLatitude")
                        .HasPrecision(8, 6)
                        .HasColumnType("decimal(8,6)");

                    b.Property<decimal>("GpsLongitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("MagassagMeter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MireVanHelyezve")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OduAzonosito")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OduTajolasa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OduTipus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OdutTartoNovenyfaj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OdutelepId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OdutelepId");

                    b.ToTable("Odu");
                });

            modelBuilder.Entity("MadarfigyeloWeb.Models.Odutelep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Azonosito")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FelelosSzemelyCim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FelelosSzemelyEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FelelosSzemelyNev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FelelosSzemelyTelefonszam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KezeloSzervezetNev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Megjegyzes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telepules")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeruletNev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UtmNegyzetKod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Odutelep");
                });

            modelBuilder.Entity("MadarfigyeloWeb.Models.Latogatas", b =>
                {
                    b.HasOne("MadarfigyeloWeb.Models.Odu", "Odu")
                        .WithMany("Latogatas")
                        .HasForeignKey("OduId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Odu");
                });

            modelBuilder.Entity("MadarfigyeloWeb.Models.Odu", b =>
                {
                    b.HasOne("MadarfigyeloWeb.Models.Odutelep", "Odutelep")
                        .WithMany("Oduk")
                        .HasForeignKey("OdutelepId");

                    b.Navigation("Odutelep");
                });

            modelBuilder.Entity("MadarfigyeloWeb.Models.Odu", b =>
                {
                    b.Navigation("Latogatas");
                });

            modelBuilder.Entity("MadarfigyeloWeb.Models.Odutelep", b =>
                {
                    b.Navigation("Oduk");
                });
#pragma warning restore 612, 618
        }
    }
}
